name: cabby
description:

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.2.0+28

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^3.2.0
  cached_network_image: ^3.2.1
  fl_chart: ^0.36.1
  flare_flutter: ^3.0.1
  flutter_custom_clippers: ^2.0.0
  flutter_speed_dial: ^3.0.5
  flutter_staggered_grid_view: ^0.4.0
  flutter_swiper_null_safety: ^1.0.2
  font_awesome_flutter: ^9.1.0
  intl: ^0.17.0
  intro_views_flutter: ^3.1.1
  introduction_screen: ^2.1.0
  share: ^2.0.4
  url_launcher: ^6.0.6
  shared_preferences: ^2.0.8
  google_fonts: ^2.1.0
  cloud_firestore: ^2.5.3
  flutter_spinkit: ^5.1.0
  firebase_auth:
  firebase_core:
  firebase_messaging: ^11.4.4
  # firebase_messaging: ^11.0.0
  # firebase_messaging: ^10.0.6
  firebase_storage: ^10.0.3
  flutter_svg:
  fluttertoast:
  shimmer: ^2.0.0
  geocoding: ^2.0.1
  geolocator: 7.7.0
  flutter_polyline_points:
  google_maps_flutter:
  pull_to_refresh:
  smooth_star_rating: ^1.1.1
  maps_toolkit:
  image_picker: ^0.8.5
  image:
  firebase_phone_auth_handler: ^0.0.8
  flutter_geofire:
  provider:
  timelines: ^0.1.0
  sign_button: ^2.0.1
  dotted_line: ^3.1.0
  http: ^0.13.3
  delayed_display: ^2.0.0
  internet_connection_checker: ^0.0.1+1
  motion_toast: ^1.2.0
  flutter_otp_text_field: ^1.0.0
  device_info_plus: ^3.2.3
  firebase_database:
  getwidget: ^2.1.0
  assets_audio_player: ^3.0.4+3
  animated_text_kit: ^4.2.1
  flutter_rating_bar: ^4.0.0
  flutterwave_payment: ^0.0.4+2
  responsive_sizer: ^3.0.8
  screenshot: ^1.2.3
  flutter_share_me: ^1.3.0
  package_info_plus: ^1.4.2
  flutter_paystack:
    git:
      url: https://github.com/definitelyme/flutter_paystack.git
      ref: patch/1.0.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  image_path_ios: "images/icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svg/
    - assets/icon/
    - assets/flare/
    - assets/images/
    - assets/images/svg/
    - assets/onboarding/
    - assets/inapp/
    - images/
    - sounds/alert.mp3
    - images/desticon.png
    - images/uberx.png
    - images/pickicon.png
  fonts:
    - family: icomoon
      fonts:
        - asset: assets/fonts/icomoon.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
